version: '3.8'
services:
  postgres_web_store:
    container_name: "postgres_web_store"
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "web-store-db"
    networks:
      - webStoreNetwork
networks:
  webStoreNetwork:
    driver: bridge
volumes:
  postgres-data: